version: '3.8'
services:
  registry:
    restart: always
    container_name: docker_registry
    image: registry:2
    volumes:
      - ./run/registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./run/keys/cert.pem:/keys/cert.pem:ro
      - ./run/registry/data:/registry
    network_mode: host
  proxy:
    container_name: docker_proxy
    image: 'nginx:alpine'
    restart: always
    volumes:
      - ./docker/nginx_parts:/etc/nginx/conf.d/parts:ro
      - ./debug/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
