version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: http://localhost:8700/v2/token
    service: registry.service
    issuer: registry.issuer
    rootcertbundle: /keys/cert.pem
health:
  storagedriver:
    enabled: true
    interval: 3600s
    threshold: 2
