version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
http:
  addr: :5000
  secret: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: http://localhost:8700/v2/token
    service: registry.service
    issuer: registry.issuer
    rootcertbundle: /keys/cert.pem
health:
  storagedriver:
    enabled: true
    interval: 3600s
    threshold: 2
