version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /certs/cert.crt
    key: /certs/cert.key
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: https://example-registry.com/v2/token
    service: example-registry.com
    issuer: example-registry.com
    rootcertbundle: /certs/cert.crt
notifications:
  endpoints:
    - name: front
      url: https://example-registry.com/v2/webhooks/events
      timeout: 2s
      threshold: 5
      backoff: 1s
health:
  storagedriver:
    enabled: true
    interval: 3600s
    threshold: 2
